GET http://localhost:3000/events

###
POST http://localhost:3000/events
Content-Type: application/json

{
    "name": "New event",
    "description": "This is a new event",
    "date": "2024-06-18T00:00:00",
    "price": 100
}

###
GET http://localhost:3000/events/74a0efaa-6485-4395-bd8a-0b4dbc10f803

###
PATCH http://localhost:3000/events/74a0efaa-6485-4395-bd8a-0b4dbc10f803
Content-Type: application/json

{
    "name": "Team meeting",
    "description": "This is a new event",
    "date": "2024-06-18T00:00:00",
    "price": 100
}